import Head from "next/head";
import styled from "@emotion/styled";

const Container = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100vh;
`;

const Title = styled.h1`
  font-size: 4rem;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Justin Park Resume</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <div>
          <Title>Welcome to Justin Resume</Title>
        </div>
      </Container>
    </>
  );
}
